language: node_js
node_js: stable
addons:
  firefox: latest
  chrome: latest
before_install:
  - "npm install -g bower"
  - "bower install"
  - "npm install -g web-component-tester"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: wct