sudo: required
language: node_js
node_js: stable
addons:
  chrome: stable
before_install:
  - npm install -g bower
  - bower install
  - npm install -g polymer-cli
  - export DISPLAY=:99.0
  - echo $DISPLAY
  - sh -e /etc/init.d/xvfb start
script: polymer test
after_script: exit
 notifications:
    slack: ehd-dev:BhmONLdq4ZJUB1zXPwCbmidO